let adminProducts=JSON.parse(localStorage.getItem('ss-products')||'null')||products;
function saveProducts(){localStorage.setItem('ss-products',JSON.stringify(adminProducts));renderAdmin()}
function renderAdmin(){document.querySelector('#productCount').textContent=adminProducts.length;document.querySelector('#adminProducts').innerHTML=adminProducts.map((p,i)=>`<tr><td>${p.id}</td><td>${p.name}</td><td>${p.cat}</td><td>${p.spec}</td><td><button onclick="editProduct(${i})">Edit</button> <button onclick="deleteProduct(${i})">Delete</button></td></tr>`).join('');const ins=JSON.parse(localStorage.getItem('ss-inquiries')||'[]');document.querySelector('#inquiryCount').textContent=ins.length;document.querySelector('#adminInquiries').innerHTML=ins.length?ins.map((x,i)=>`<tr><td>${(x.date||'').slice(0,10)}</td><td>${x.name||''}</td><td>${x.company||''}</td><td>${x.email||''}<br>${x.whatsapp||''}</td><td>${x.product||''}<br>${x.message||''}</td><td><button onclick="deleteInquiry(${i})">Delete</button></td></tr>`).join(''):'<tr><td colspan="6">No inquiries yet.</td></tr>'}
function addProduct(){const name=prompt('Product name');if(!name)return;adminProducts.push({id:prompt('SKU','SS-NEW')||'SS-NEW',name,cat:prompt('Category: vases, candles, holders or tableware','vases')||'vases',spec:prompt('Material and size','Stoneware · Custom size')||'',pos:'50% 50%'});saveProducts()}
function editProduct(i){const p=adminProducts[i];p.name=prompt('Product name',p.name)||p.name;p.spec=prompt('Specification',p.spec)||p.spec;p.cat=prompt('Category',p.cat)||p.cat;saveProducts()}
function deleteProduct(i){if(confirm('Delete this product?')){adminProducts.splice(i,1);saveProducts()}}
function deleteInquiry(i){const x=JSON.parse(localStorage.getItem('ss-inquiries')||'[]');x.splice(i,1);localStorage.setItem('ss-inquiries',JSON.stringify(x));renderAdmin()}
function clearInquiries(){if(confirm('Delete all stored inquiries?')){localStorage.removeItem('ss-inquiries');renderAdmin()}}
function exportData(){const data={products:adminProducts,inquiries:JSON.parse(localStorage.getItem('ss-inquiries')||'[]')};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='summer-secret-data.json';a.click()}
renderAdmin();
